// Generated by generate_simulator_abi_bindings.py; do not edit.
// Candidate/shadow binding only. Including this file does not activate V0.4.
#ifndef RTCORE_SIMULATOR_ABI_V04_GENERATED_H
#define RTCORE_SIMULATOR_ABI_V04_GENERATED_H

#include <array>
#include <cstddef>
#include <cstdint>

namespace rtcore {
namespace abi_v04 {

static constexpr const char kProfileId[] = "RTCORE_SIMULATOR_ABI_V04_FULL_TRACE_EFFECT_128B";
static constexpr const char kProfileVersion[] = "0.4.0";
static constexpr const char kLayoutId[] = "RTCORE_HANDOFF_PROFILE_V04_FULL_TRACE_EFFECT_128B";
static constexpr uint32_t kLayoutValue = 0x00000003u;
static constexpr uint32_t kLayoutVersion = 0x00000001u;
static constexpr std::size_t kLaneSlotBytes = 128u;
static constexpr std::size_t kWordCount = 32u;
static constexpr const char kSourceInputSha256[] = "e12c6575d8f05ff11f93751ead813e3f44c2fea1e0b73c445132d166c783a000";

struct field_spec {
  uint8_t word;
  uint8_t lsb;
  uint8_t width;
  uint32_t mask;
};

struct named_field_spec {
  const char *name;
  field_spec spec;
};

struct fixture_field {
  field_spec spec;
  uint32_t value;
};

static constexpr field_spec kContextAddressLow32 = {0, 0, 32, 0xffffffffu};
static constexpr field_spec kContextAddressHigh32 = {1, 0, 32, 0xffffffffu};
static constexpr field_spec kTraversableReferenceLow32 = {2, 0, 32, 0xffffffffu};
static constexpr field_spec kTraversableReferenceHigh32 = {3, 0, 32, 0xffffffffu};
static constexpr field_spec kWorldRayOriginXFp32 = {4, 0, 32, 0xffffffffu};
static constexpr field_spec kWorldRayOriginYFp32 = {5, 0, 32, 0xffffffffu};
static constexpr field_spec kWorldRayOriginZFp32 = {6, 0, 32, 0xffffffffu};
static constexpr field_spec kRayTminFp32 = {7, 0, 32, 0xffffffffu};
static constexpr field_spec kWorldRayDirectionXFp32 = {8, 0, 32, 0xffffffffu};
static constexpr field_spec kWorldRayDirectionYFp32 = {9, 0, 32, 0xffffffffu};
static constexpr field_spec kWorldRayDirectionZFp32 = {10, 0, 32, 0xffffffffu};
static constexpr field_spec kLaunchRayTmaxFp32 = {11, 0, 32, 0xffffffffu};
static constexpr field_spec kRayFlags = {12, 0, 32, 0xffffffffu};
static constexpr field_spec kCullMask = {13, 0, 8, 0x000000ffu};
static constexpr field_spec kSbtRecordOffset = {13, 8, 4, 0x00000f00u};
static constexpr field_spec kSbtRecordStride = {13, 12, 4, 0x0000f000u};
static constexpr field_spec kMissIndex = {13, 16, 16, 0xffff0000u};
static constexpr field_spec kInstanceMetadataReferenceLow32 = {14, 0, 32, 0xffffffffu};
static constexpr field_spec kInstanceMetadataReferenceHigh32 = {15, 0, 32, 0xffffffffu};
static constexpr field_spec kInstanceSbtContribution = {16, 0, 32, 0xffffffffu};
static constexpr field_spec kGeometryIndex = {17, 0, 32, 0xffffffffu};
static constexpr field_spec kBoundaryRayTmaxFp32 = {18, 0, 32, 0xffffffffu};
static constexpr field_spec kPrimitiveIndex = {19, 0, 32, 0xffffffffu};
static constexpr field_spec kInstanceIndex = {20, 0, 32, 0xffffffffu};
static constexpr field_spec kInstanceCustomIndex = {21, 0, 32, 0xffffffffu};
static constexpr field_spec kHitKind = {22, 0, 8, 0x000000ffu};
static constexpr field_spec kProceduralAnyHitEligible = {22, 8, 1, 0x00000100u};
static constexpr field_spec kInputAttributeWordCount = {23, 0, 8, 0x000000ffu};
static constexpr field_spec kInputAttributeLocation = {23, 8, 8, 0x0000ff00u};
static constexpr field_spec kInputAttributeFormat = {23, 16, 8, 0x00ff0000u};
static constexpr field_spec kCommitRetainedCandidate = {24, 0, 1, 0x00000001u};
static constexpr field_spec kAcceptedReportedHitValid = {24, 1, 1, 0x00000002u};
static constexpr field_spec kTerminateSearch = {24, 2, 1, 0x00000004u};
static constexpr field_spec kReportedTFp32 = {25, 0, 32, 0xffffffffu};
static constexpr field_spec kReportedHitKind = {26, 0, 8, 0x000000ffu};
static constexpr field_spec kReportedAttributeWordCount = {26, 8, 8, 0x0000ff00u};
static constexpr field_spec kReportedAttributeFormat = {26, 16, 8, 0x00ff0000u};
static constexpr field_spec kInlineAttributeWord0 = {28, 0, 32, 0xffffffffu};
static constexpr field_spec kInlineAttributeWord1 = {29, 0, 32, 0xffffffffu};
static constexpr field_spec kInlineAttributeWord2 = {30, 0, 32, 0xffffffffu};
static constexpr field_spec kInlineAttributeWord3 = {31, 0, 32, 0xffffffffu};

static constexpr named_field_spec kFields[] = {
    {"context_address_low32", kContextAddressLow32},
    {"context_address_high32", kContextAddressHigh32},
    {"traversable_reference_low32", kTraversableReferenceLow32},
    {"traversable_reference_high32", kTraversableReferenceHigh32},
    {"world_ray_origin_x_fp32", kWorldRayOriginXFp32},
    {"world_ray_origin_y_fp32", kWorldRayOriginYFp32},
    {"world_ray_origin_z_fp32", kWorldRayOriginZFp32},
    {"ray_tmin_fp32", kRayTminFp32},
    {"world_ray_direction_x_fp32", kWorldRayDirectionXFp32},
    {"world_ray_direction_y_fp32", kWorldRayDirectionYFp32},
    {"world_ray_direction_z_fp32", kWorldRayDirectionZFp32},
    {"launch_ray_tmax_fp32", kLaunchRayTmaxFp32},
    {"ray_flags", kRayFlags},
    {"cull_mask", kCullMask},
    {"sbt_record_offset", kSbtRecordOffset},
    {"sbt_record_stride", kSbtRecordStride},
    {"miss_index", kMissIndex},
    {"instance_metadata_reference_low32", kInstanceMetadataReferenceLow32},
    {"instance_metadata_reference_high32", kInstanceMetadataReferenceHigh32},
    {"instance_sbt_contribution", kInstanceSbtContribution},
    {"geometry_index", kGeometryIndex},
    {"boundary_ray_tmax_fp32", kBoundaryRayTmaxFp32},
    {"primitive_index", kPrimitiveIndex},
    {"instance_index", kInstanceIndex},
    {"instance_custom_index", kInstanceCustomIndex},
    {"hit_kind", kHitKind},
    {"procedural_any_hit_eligible", kProceduralAnyHitEligible},
    {"input_attribute_word_count", kInputAttributeWordCount},
    {"input_attribute_location", kInputAttributeLocation},
    {"input_attribute_format", kInputAttributeFormat},
    {"commit_retained_candidate", kCommitRetainedCandidate},
    {"accepted_reported_hit_valid", kAcceptedReportedHitValid},
    {"terminate_search", kTerminateSearch},
    {"reported_t_fp32", kReportedTFp32},
    {"reported_hit_kind", kReportedHitKind},
    {"reported_attribute_word_count", kReportedAttributeWordCount},
    {"reported_attribute_format", kReportedAttributeFormat},
    {"inline_attribute_word_0", kInlineAttributeWord0},
    {"inline_attribute_word_1", kInlineAttributeWord1},
    {"inline_attribute_word_2", kInlineAttributeWord2},
    {"inline_attribute_word_3", kInlineAttributeWord3},
};
static constexpr std::size_t kFieldCount = sizeof(kFields) / sizeof(kFields[0]);
static constexpr uint32_t kReservedMasks[kWordCount] = {
    0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0xfffffe00u, 0xff000000u, 0xfffffff8u, 0x00000000u, 0xff000000u, 0xffffffffu, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u
};
static constexpr uint32_t kCompactResultReservedMask = 0x7fffff00u;
static constexpr field_spec kCompactResultRtReturnReason = {0, 0, 8, 0x000000ffu};
static constexpr field_spec kCompactResultCompletionValid = {0, 31, 1, 0x80000000u};

static constexpr uint32_t kReasonNoneOrInvalid = 0x00u;
static constexpr uint32_t kReasonMiss = 0x01u;
static constexpr uint32_t kReasonClosestHitReady = 0x02u;
static constexpr uint32_t kReasonAnyHitRequired = 0x03u;
static constexpr uint32_t kReasonIntersectionRequired = 0x04u;
static constexpr uint32_t kReasonTraceDoneNoShader = 0x05u;
static constexpr uint32_t kReasonReservedFaultNotProduced = 0x06u;
static constexpr uint32_t kReasonReservedUnsupportedNotProduced = 0x07u;

static constexpr const char kCanonicalFixtureId[] = "RTCORE_SIMULATOR_ABI_V04_CANONICAL_INTERSECTION_RETURN";
static constexpr fixture_field kCanonicalFixtureFields[] = {
    {kContextAddressLow32, 0x55667788u},
    {kContextAddressHigh32, 0x11223344u},
    {kTraversableReferenceLow32, 0x44332210u},
    {kTraversableReferenceHigh32, 0x88776655u},
    {kWorldRayOriginXFp32, 0x3f800000u},
    {kWorldRayOriginYFp32, 0xc0000000u},
    {kWorldRayOriginZFp32, 0x40600000u},
    {kRayTminFp32, 0x3e800000u},
    {kWorldRayDirectionXFp32, 0x00000000u},
    {kWorldRayDirectionYFp32, 0x3f800000u},
    {kWorldRayDirectionZFp32, 0xbf800000u},
    {kLaunchRayTmaxFp32, 0x42c80000u},
    {kRayFlags, 0x0000a5a5u},
    {kCullMask, 0x0000007fu},
    {kSbtRecordOffset, 0x0000000au},
    {kSbtRecordStride, 0x00000005u},
    {kMissIndex, 0x00001234u},
    {kInstanceMetadataReferenceLow32, 0x89abcdefu},
    {kInstanceMetadataReferenceHigh32, 0x01234567u},
    {kInstanceSbtContribution, 0x10203040u},
    {kGeometryIndex, 0x50607080u},
    {kBoundaryRayTmaxFp32, 0x41400000u},
    {kPrimitiveIndex, 0x0badc0deu},
    {kInstanceIndex, 0x13572468u},
    {kInstanceCustomIndex, 0x24681357u},
    {kHitKind, 0x00000000u},
    {kProceduralAnyHitEligible, 0x00000001u},
    {kInputAttributeWordCount, 0x00000000u},
    {kInputAttributeLocation, 0x00000000u},
    {kInputAttributeFormat, 0x00000000u},
    {kCommitRetainedCandidate, 0x00000000u},
    {kAcceptedReportedHitValid, 0x00000001u},
    {kTerminateSearch, 0x00000001u},
    {kReportedTFp32, 0x40e00000u},
    {kReportedHitKind, 0x0000002au},
    {kReportedAttributeWordCount, 0x00000004u},
    {kReportedAttributeFormat, 0x00000002u},
    {kInlineAttributeWord0, 0xdeadbeefu},
    {kInlineAttributeWord1, 0x01020304u},
    {kInlineAttributeWord2, 0x55667788u},
    {kInlineAttributeWord3, 0xa5a55a5au},
};
static constexpr std::size_t kCanonicalFixtureFieldCount =
    sizeof(kCanonicalFixtureFields) / sizeof(kCanonicalFixtureFields[0]);
static constexpr uint32_t kCanonicalFixtureWords[kWordCount] = {
    0x55667788u, 0x11223344u, 0x44332210u, 0x88776655u, 0x3f800000u, 0xc0000000u, 0x40600000u, 0x3e800000u, 0x00000000u, 0x3f800000u, 0xbf800000u, 0x42c80000u, 0x0000a5a5u, 0x12345a7fu, 0x89abcdefu, 0x01234567u, 0x10203040u, 0x50607080u, 0x41400000u, 0x0badc0deu, 0x13572468u, 0x24681357u, 0x00000100u, 0x00000000u, 0x00000006u, 0x40e00000u, 0x0002042au, 0x00000000u, 0xdeadbeefu, 0x01020304u, 0x55667788u, 0xa5a55a5au
};
static constexpr uint32_t kCanonicalFixtureCompactResult = 0x80000004u;
static constexpr uint32_t kCanonicalFixtureBoundary =
    kReasonIntersectionRequired;

inline bool value_fits(field_spec field, uint32_t value) {
  return field.width == 32 || value < (uint32_t{1} << field.width);
}

inline bool insert_field(std::array<uint32_t, kWordCount> &words,
                         field_spec field, uint32_t value) {
  if (field.word >= kWordCount || !value_fits(field, value)) return false;
  words[field.word] = (words[field.word] & ~field.mask) |
                      ((value << field.lsb) & field.mask);
  return true;
}

inline uint32_t extract_field(const std::array<uint32_t, kWordCount> &words,
                              field_spec field) {
  return (words[field.word] & field.mask) >> field.lsb;
}

inline bool validate_reserved_zero(
    const std::array<uint32_t, kWordCount> &words) {
  for (std::size_t index = 0; index < kWordCount; ++index) {
    if (words[index] & kReservedMasks[index]) return false;
  }
  return true;
}

inline std::array<uint8_t, kLaneSlotBytes> encode_words_le(
    const std::array<uint32_t, kWordCount> &words) {
  std::array<uint8_t, kLaneSlotBytes> image{};
  for (std::size_t word = 0; word < kWordCount; ++word) {
    for (std::size_t byte = 0; byte < 4; ++byte) {
      image[word * 4 + byte] =
          static_cast<uint8_t>((words[word] >> (byte * 8)) & 0xffu);
    }
  }
  return image;
}

inline std::array<uint32_t, kWordCount> decode_words_le(
    const std::array<uint8_t, kLaneSlotBytes> &image) {
  std::array<uint32_t, kWordCount> words{};
  for (std::size_t word = 0; word < kWordCount; ++word) {
    for (std::size_t byte = 0; byte < 4; ++byte) {
      words[word] |= static_cast<uint32_t>(image[word * 4 + byte])
                     << (byte * 8);
    }
  }
  return words;
}

inline bool pack_compact_result(uint32_t reason, bool completion_valid,
                                uint32_t *result) {
  if (result == NULL || !(reason == kReasonNoneOrInvalid || reason == kReasonMiss || reason == kReasonClosestHitReady || reason == kReasonAnyHitRequired || reason == kReasonIntersectionRequired || reason == kReasonTraceDoneNoShader || reason == kReasonReservedFaultNotProduced || reason == kReasonReservedUnsupportedNotProduced)) return false;
  uint32_t value = (reason << kCompactResultRtReturnReason.lsb) &
                   kCompactResultRtReturnReason.mask;
  if (completion_valid) {
    value |= (uint32_t{1} << kCompactResultCompletionValid.lsb) &
             kCompactResultCompletionValid.mask;
  }
  if (value & kCompactResultReservedMask) return false;
  *result = value;
  return true;
}

inline bool is_legal_traversal_effect(uint32_t reason, uint32_t effect) {
  if (reason == kReasonAnyHitRequired) return effect == 0x0u || effect == 0x1u || effect == 0x5u;
  if (reason == kReasonIntersectionRequired) return effect == 0x0u || effect == 0x2u || effect == 0x6u;
  return false;
}

}  // namespace abi_v04
}  // namespace rtcore

#endif  // RTCORE_SIMULATOR_ABI_V04_GENERATED_H
